name: robocasa_umi
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.17
  - pip=25.1.1
  - numpy=1.23.2
  - scipy=1.9.1
  - numba=0.56.4
  - pandas=2.2.3
  - ipykernel=6.23
  - matplotlib=3.10.3
  - av=10.0
  - k3d=2.15
  - pyyaml=6.0
  - tqdm=4.65
  - zarr=2.16
  - numcodecs=0.11
  - hydra-core=1.2.0
  - wandb=0.13.3
  - dill=0.3.7
  - einops=0.6.1
  - diffusers=0.11.1
  - scikit-video=1.1
  # trick to avoid cpu affinity issue described in https://github.com/pytorch/pytorch/issues/99625
  - llvm-openmp=14
  - python-lmdb=1.4
  - timm=0.9.7
  - scikit-fda=0.9
  - cython=0.29
  - accelerate=0.24
  - boto3=1.33
  - exiftool=12
  - aiohttp=3.9
  - aiofiles=23.2
  - pip:
    - ray[default]==2.8.0
    - threadpoolctl==3.2
    - v4l2py==2.2
    - ur-rtde==1.5.6
    # requires apt install libspnav-dev spacenavd; systemctl start spacenavd
    - atomics==1.0.2
    - pynput==1.7.6
    - fastcrc==0.2
    - imagecodecs==2023.9.18
    # requires mujoco py dependencies libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
    - free-mujoco-py==2.1.6
    # implicitly depend on conda package exiftool
    - PyExifTool==0.5
    - open-clip-torch==2.24.0
    - opencv-python==4.11.0.86
    - torch==2.2.1