ckpt_folder: train_diffusion_unet_clip_train_closedrawer_fd_scores
ckpt_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/epoch_350_step_28079.ckpt
task_name: train_diffusion_unet_clip_train_closedrawer_fd_scores_original_env

name: eval_diffusion_unet_clip
_target_: diffusion_policy.workspace.get_eval_rollout_FD_scores_diffusion_unet_clip_workspace_original_env.EvalComputeFDScoresDiffusionUnetImageWorkspace


fail_detect:
  task_name: closedrawer_clip
  base_policy_ckpt_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/epoch_350_step_28079.ckpt
  save_obs_embeds_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/obs_embeds.pt
  save_score_network_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/fd_score_network.ckpt


num_inference_steps: 50

environment_file: "demo_gentex_im128_randcams_100_mg_envs.pkl"
# environment_file: "demo_gentex_im256_randcams_100_train_envs.pkl"
num_experiments: 50

execution_horizon: 16

number_of_tasks: 50
max_traj_len: 700
dataset_mode: "test"

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/experiments/${task_name}
  sweep:
    dir: data/experiments/${task_name}
    subdir: ${hydra.job.num}