ckpt_folder: train_diffusion_unet_clip_train_closedrawer_fd_scores
ckpt_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/epoch_350_step_28079.ckpt
task_name: train_diffusion_unet_clip_train_closedrawer_fd_scores_original_env

name: eval_diffusion_unet_clip
_target_: diffusion_policy.workspace.compute_fd_scores_on_eval_rollouts_diffusion_unet_clip_workspace_original_env.EvalComputeFDScoresDiffusionUnetImageWorkspace


fail_detect:
  task_name: closedrawer_clip
  base_policy_ckpt_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/epoch_350_step_28079.ckpt
  save_obs_embeds_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/obs_embeds.pt
  save_score_network_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/fd_score_network.ckpt


num_inference_steps: 50

environment_file: "demo_gentex_im128_randcams_100_mg_envs.pkl"
# environment_file: "demo_gentex_im256_randcams_100_train_envs.pkl"
num_experiments: 50

execution_horizon: 16

number_of_tasks: 50
max_traj_len: 700
dataset_mode: "test"

task:
  abs_action: false
  dataset:
    _target_: diffusion_policy.dataset.robocasa_replay_image_dataset.RobocasaReplayImageDataset
    abs_action: false
    dataset_path: datasets/v0.1/single_stage/kitchen_drawer/CloseDrawer/2024-04-30/demo_gentex_im128_randcams_im256.hdf5
    horizon: 16
    n_obs_steps: 2
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 7
      obs:
        robot0_agentview_right_image:
          shape:
          - 3
          - 256
          - 256
          type: rgb
        robot0_agentview_left_image:
          shape:
          - 3
          - 256
          - 256
          type: rgb
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 256
          - 256
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
    use_cache: true
    val_ratio: 0.02
  dataset_path: ../robocasa/datasets_first/v0.1/single_stage/kitchen_drawer/CloseDrawer/2024-04-30/demo_im256.hdf5
  dataset_type: ph
  env_runner:
    _target_: diffusion_policy.env_runner.robocasa_dp_clip_eval_image_runner.EvalRobocasaImageRunner
    abs_action: false
    crf: 22
    dataset_path: ../robocasa/datasets_first/v0.1/single_stage/kitchen_drawer/CloseDrawer/2024-04-30/demo_im256.hdf5
    fps: 10
    max_steps: 400
    n_action_steps: 16
    n_envs: 1
    n_obs_steps: 2
    n_test: 0
    n_test_vis: 1
    n_train: 0
    n_train_vis: 0
    past_action: false
    render_obs_key: robot0_agentview_right_image
    shape_meta:
      action:
        shape:
        - 7
      obs:
        robot0_agentview_right_image:
          shape:
          - 3
          - 256
          - 256
          type: rgb
        robot0_agentview_left_image:
          shape:
          - 3
          - 256
          - 256
          type: rgb
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 256
          - 256
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  name: closedrawer_image
  shape_meta:
    action:
      shape:
      - 7
    obs:
      robot0_agentview_right_image:
        shape:
        - 3
        - 256
        - 256
        type: rgb
      robot0_agentview_left_image:
        shape:
        - 3
        - 256
        - 256
        type: rgb
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 256
        - 256
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
  task_name: closedrawer

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/experiments/${task_name}
  sweep:
    dir: data/experiments/${task_name}
    subdir: ${hydra.job.num}