ckpt_folder: train_diffusion_unet_clip_train_closedrawer
ckpt_path: data/outputs/2025.06.04/${ckpt_folder}/checkpoints/epoch_350_step_28079.ckpt
task_name: ${ckpt_folder}_original_env

name: eval_diffusion_unet_clip
_target_: diffusion_policy.workspace.eval_diffusion_unet_clip_workspace_original_env.EvalDiffusionUnetImageWorkspace

num_inference_steps: 50

environment_file: "demo_gentex_im128_randcams_100_mg_envs.pkl"
# environment_file: "demo_gentex_im256_randcams_100_train_envs.pkl"
num_experiments: 50

execution_horizon: 16

number_of_tasks: 50
max_traj_len: 1500
dataset_mode: "test"

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/experiments/${task_name}
  sweep:
    dir: data/experiments/${task_name}
    subdir: ${hydra.job.num}