defaults:
  - _self_
  - task: train_clip

task_name: train_diffusion_unet_clip_closedrawer
name: train_diffusion_unet_clip
_target_: diffusion_policy.workspace.retrain_faildetect_on_dagger_workspace.FailDetectWorkspace


experiment_name: train_diffusion_unet_clip
experiment_tag: ST_OOD_DAgger
dagger_episode: 0
dagger_data_path: data/outputs/${experiment_tag}_${name}_${task.name}/dagger_episode_${dagger_episode}/dagger_data
processed_dagger_data_path: data/outputs/${experiment_tag}_${name}_${task.name}/dagger_episode_${dagger_episode}/processed_dagger_data
N_dagger_eps: 25

dagger:
  ckpt_folder: 'finetune_w_human_only=True_from_base_after_dagger'
  ckpt_name: 'latest'
  ckpt_path: data/outputs/${experiment_tag}_${name}_${task_name}/${dagger.ckpt_folder}/checkpoints/${dagger.ckpt_name}.ckpt
  dagger_episode: 0
  dagger_data_path: data/outputs/${experiment_tag}_${name}_${task_name}/dagger_episode_${dagger.dagger_episode}/dagger_data
  processed_dagger_data_path: data/outputs/${experiment_tag}_${name}_${task_name}/dagger_episode_${dagger.dagger_episode}/processed_dagger_data
  N_dagger_eps: 25

FD_task_name: ${task.name}
FD_base_policy_ckpt_path: data/outputs/${experiment_tag}_${name}_${task_name}/${dagger.ckpt_folder}/checkpoints/${dagger.ckpt_name}.ckpt
FD_save_obs_embeds_path: data/outputs/${experiment_tag}_${name}_${FD_task_name}/base_policy/obs_embeds.pt
FD_original_score_network_path: data/outputs/${experiment_tag}_${name}_${FD_task_name}/base_policy/fd_score_network.ckpt
# FD_save_dagger_succ_obs_embeds_path: data/outputs/${experiment_tag}_${name}_${task_name}/${dagger.ckpt_folder}/checkpoints/dagger_succ_obs_embeds
# FD_save_dagger_fail_obs_embeds_path: data/outputs/${experiment_tag}_${name}_${task_name}/${dagger.ckpt_folder}/checkpoints/dagger_fail_obs_embeds

FD_save_dagger_auton_succ_obs_embeds_path: data/outputs/${experiment_tag}_${name}_${task_name}/${dagger.ckpt_folder}/checkpoints/dagger_auton_succ_obs_embeds.pt
FD_save_dagger_combined_succ_obs_embeds_path: data/outputs/${experiment_tag}_${name}_${task_name}/${dagger.ckpt_folder}/checkpoints/dagger_combined_succ_obs_embeds.pt
FD_save_dagger_human_succ_obs_embeds_path: data/outputs/${experiment_tag}_${name}_${task_name}/${dagger.ckpt_folder}/checkpoints/dagger_human_succ_obs_embeds.pt
FD_save_dagger_fail_obs_embeds_path: data/outputs/${experiment_tag}_${name}_${task_name}/${dagger.ckpt_folder}/checkpoints/dagger_fail_obs_embeds.pt


# FD_save_score_network_path: data/outputs/${experiment_tag}_${name}_${task_name}/${dagger.ckpt_folder}/fd_score_network.ckpt
added_data_type: 'auton'
FD_save_score_network_path: data/outputs/${experiment_tag}_${name}_${task_name}/${dagger.ckpt_folder}/fd_${added_data_type}_added_score_network.ckpt

eval_num_inference_steps: 50
# FD_base_policy_ckpt_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_example/checkpoints/epoch_250_step_33884.ckpt
# FD_save_obs_embeds_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_example/checkpoints/obs_embeds.pt
# FD_save_score_network_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_example/checkpoints/fd_score_network.ckpt


hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${experiment_tag}_${name}_${FD_task_name}/score_network
  sweep:
    dir: data/outputs/${experiment_tag}_${name}_${FD_task_name}/score_network
    subdir: ${hydra.job.num}