defaults:
  - _self_
  - task: train_clip

name: train_diffusion_unet_clip
experiment_tag: ST_OOD_DAgger
_target_: diffusion_policy.workspace.train_deminf_workspace.TrainDemInfWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"


dataloader:
  batch_size: 36
  num_workers: 24
  shuffle: True
  pin_memory: True
  persistent_workers: True

optimizer:
  _target_: torch.optim.AdamW
  lr: 3.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: False
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 2000
  num_epochs: 1000
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  freeze_encoder: False
  # training loop control
  # in epochs
  rollout_every: 0
  checkpoint_every: 100
  val_every: 100
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0


logging:
  project: deminf
  resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 5
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

# multi_run:
#   run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
#   wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${experiment_tag}_${name}
  run:
    dir: data/outputs/${experiment_tag}_${name}_${task_name}/deminf_curator
  sweep:
    dir: data/outputs/${experiment_tag}_${name}_${task_name}/deminf_curator
    subdir: ${hydra.job.num}

