defaults:
  - _self_
  - task: train_clip

task_name: train_faildetect_unet_clip_closedrawer
name: train_faildetect_unet_clip
_target_: diffusion_policy.workspace.train_faildetect_workspace.FailDetectWorkspace

# FD_task_name: closedrawer_clip
# FD_base_policy_ckpt_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/epoch_350_step_28079.ckpt
# FD_save_obs_embeds_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/obs_embeds.pt
# FD_save_score_network_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_closedrawer/checkpoints/fd_score_network.ckpt

FD_task_name: PnPCabToCounter_clip
FD_base_policy_ckpt_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_example/checkpoints/epoch_250_step_33884.ckpt
FD_save_obs_embeds_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_example/checkpoints/obs_embeds.pt
FD_save_score_network_path: data/outputs/2025.06.04/train_diffusion_unet_clip_train_example/checkpoints/fd_score_network.ckpt


hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%H.%M.%S}_{name}_${task_name}/${now:%H.%M.%S}
  sweep:
    dir: data/outputs/${now:%H.%M.%S}_{name}_${task_name}/${now:%H.%M.%S}
    subdir: ${hydra.job.num}